-- Require a public student profile and introduce a fresh MED-1 leaderboard season.
-- Existing quiz progress remains untouched. Lifetime best scores are snapshotted
-- before the new season starts, and the season begins at migration time.

ALTER TABLE public.user_preferences
  ADD COLUMN IF NOT EXISTS profile_setup_version INTEGER NOT NULL DEFAULT 0;

ALTER TABLE public.user_preferences
  ALTER COLUMN anonymous SET DEFAULT false;

UPDATE public.user_preferences
SET anonymous = false
WHERE anonymous = true;

ALTER TABLE public.user_preferences
  DROP CONSTRAINT IF EXISTS user_preferences_public_identity_required;

ALTER TABLE public.user_preferences
  ADD CONSTRAINT user_preferences_public_identity_required
  CHECK (
    anonymous = false
    AND (
      profile_setup_version = 0
      OR (
        profile_setup_version >= 1
        AND NULLIF(btrim(nickname), '') IS NOT NULL
        AND NULLIF(avatar_id, '') IS NOT NULL
      )
    )
  );

CREATE UNIQUE INDEX IF NOT EXISTS user_preferences_nickname_unique
  ON public.user_preferences (lower(btrim(nickname)))
  WHERE NULLIF(btrim(nickname), '') IS NOT NULL;

ALTER TABLE public.user_mcq_progress
  ADD COLUMN IF NOT EXISTS attempt_id UUID,
  ADD COLUMN IF NOT EXISTS attempt_started_at TIMESTAMPTZ;

CREATE TABLE IF NOT EXISTS public.leaderboard_seasons (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section           TEXT NOT NULL CHECK (section IN ('401', '402')),
  name              TEXT NOT NULL,
  scope_topic_label TEXT,
  starts_at         TIMESTAMPTZ NOT NULL,
  ends_at           TIMESTAMPTZ,
  active            BOOLEAN NOT NULL DEFAULT true,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  CHECK (ends_at IS NULL OR ends_at > starts_at)
);

CREATE UNIQUE INDEX IF NOT EXISTS leaderboard_seasons_one_active_per_section
  ON public.leaderboard_seasons (section)
  WHERE active;

CREATE TABLE IF NOT EXISTS public.user_lifetime_scores (
  user_id         UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  section         TEXT NOT NULL,
  topic_label     TEXT NOT NULL,
  source_id       TEXT NOT NULL,
  best_score      INTEGER NOT NULL CHECK (best_score >= 0),
  total_questions INTEGER,
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, section, topic_label, source_id)
);

CREATE TABLE IF NOT EXISTS public.user_season_scores (
  season_id       BIGINT NOT NULL REFERENCES public.leaderboard_seasons(id) ON DELETE CASCADE,
  user_id         UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  topic_label     TEXT NOT NULL,
  source_id       TEXT NOT NULL,
  best_score      INTEGER NOT NULL CHECK (best_score >= 0),
  total_questions INTEGER,
  attempt_id      UUID,
  earned_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (season_id, user_id, topic_label, source_id)
);

ALTER TABLE public.leaderboard_seasons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_lifetime_scores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_season_scores ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.leaderboard_seasons FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.user_lifetime_scores FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.user_season_scores FROM PUBLIC, anon, authenticated;

INSERT INTO public.user_lifetime_scores (
  user_id,
  section,
  topic_label,
  source_id,
  best_score,
  total_questions,
  updated_at
)
SELECT
  progress.user_id,
  progress.section,
  progress.topic_label,
  progress.source_id,
  GREATEST(COALESCE(progress.score, 0), 0),
  progress.total_questions,
  COALESCE(progress.updated_at, now())
FROM public.user_mcq_progress progress
WHERE progress.score IS NOT NULL
ON CONFLICT (user_id, section, topic_label, source_id)
DO UPDATE SET
  best_score = GREATEST(public.user_lifetime_scores.best_score, EXCLUDED.best_score),
  total_questions = COALESCE(EXCLUDED.total_questions, public.user_lifetime_scores.total_questions),
  updated_at = GREATEST(public.user_lifetime_scores.updated_at, EXCLUDED.updated_at);

INSERT INTO public.leaderboard_seasons (
  section,
  name,
  scope_topic_label,
  starts_at,
  active
)
SELECT
  '401',
  'MED-1 Midterm',
  'MED 401-1 MCQs',
  transaction_timestamp(),
  true
WHERE NOT EXISTS (
  SELECT 1
  FROM public.leaderboard_seasons season
  WHERE season.section = '401'
    AND season.active
);

CREATE SCHEMA IF NOT EXISTS private;
REVOKE ALL ON SCHEMA private FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION private.capture_quiz_best_scores()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  current_user_id UUID := (SELECT auth.uid());
  active_season public.leaderboard_seasons%ROWTYPE;
BEGIN
  IF current_user_id IS NULL OR NEW.user_id <> current_user_id THEN
    RETURN NEW;
  END IF;

  IF NEW.completed IS DISTINCT FROM true OR NEW.score IS NULL THEN
    RETURN NEW;
  END IF;

  INSERT INTO public.user_lifetime_scores (
    user_id,
    section,
    topic_label,
    source_id,
    best_score,
    total_questions,
    updated_at
  )
  VALUES (
    NEW.user_id,
    NEW.section,
    NEW.topic_label,
    NEW.source_id,
    GREATEST(NEW.score, 0),
    NEW.total_questions,
    now()
  )
  ON CONFLICT (user_id, section, topic_label, source_id)
  DO UPDATE SET
    best_score = GREATEST(public.user_lifetime_scores.best_score, EXCLUDED.best_score),
    total_questions = COALESCE(EXCLUDED.total_questions, public.user_lifetime_scores.total_questions),
    updated_at = now();

  SELECT season.*
  INTO active_season
  FROM public.leaderboard_seasons season
  WHERE season.section = NEW.section
    AND season.active
    AND season.starts_at <= now()
    AND (season.ends_at IS NULL OR season.ends_at > now())
    AND (season.scope_topic_label IS NULL OR season.scope_topic_label = NEW.topic_label)
  ORDER BY season.starts_at DESC
  LIMIT 1;

  IF active_season.id IS NOT NULL
    AND NEW.attempt_id IS NOT NULL
    AND NEW.attempt_started_at IS NOT NULL
    AND NEW.attempt_started_at >= active_season.starts_at
  THEN
    INSERT INTO public.user_season_scores (
      season_id,
      user_id,
      topic_label,
      source_id,
      best_score,
      total_questions,
      attempt_id,
      earned_at,
      updated_at
    )
    VALUES (
      active_season.id,
      NEW.user_id,
      NEW.topic_label,
      NEW.source_id,
      GREATEST(NEW.score, 0),
      NEW.total_questions,
      NEW.attempt_id,
      COALESCE(NEW.completed_at, now()),
      now()
    )
    ON CONFLICT (season_id, user_id, topic_label, source_id)
    DO UPDATE SET
      best_score = GREATEST(public.user_season_scores.best_score, EXCLUDED.best_score),
      total_questions = COALESCE(EXCLUDED.total_questions, public.user_season_scores.total_questions),
      attempt_id = CASE
        WHEN EXCLUDED.best_score >= public.user_season_scores.best_score THEN EXCLUDED.attempt_id
        ELSE public.user_season_scores.attempt_id
      END,
      earned_at = CASE
        WHEN EXCLUDED.best_score >= public.user_season_scores.best_score THEN EXCLUDED.earned_at
        ELSE public.user_season_scores.earned_at
      END,
      updated_at = now();
  END IF;

  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION private.capture_quiz_best_scores() FROM PUBLIC, anon, authenticated;

DROP TRIGGER IF EXISTS capture_quiz_best_scores ON public.user_mcq_progress;

CREATE TRIGGER capture_quiz_best_scores
AFTER INSERT OR UPDATE OF completed, score, total_questions, attempt_id, attempt_started_at
ON public.user_mcq_progress
FOR EACH ROW
EXECUTE FUNCTION private.capture_quiz_best_scores();

CREATE OR REPLACE FUNCTION public.complete_profile_setup(
  p_nickname TEXT,
  p_avatar_id TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  current_user_id UUID := (SELECT auth.uid());
  clean_nickname TEXT := btrim(regexp_replace(COALESCE(p_nickname, ''), '\s+', ' ', 'g'));
  saved_preferences public.user_preferences%ROWTYPE;
BEGIN
  IF current_user_id IS NULL THEN
    RAISE EXCEPTION 'Sign in is required.' USING ERRCODE = '42501';
  END IF;

  IF char_length(clean_nickname) NOT BETWEEN 2 AND 24
    OR clean_nickname ~ '[[:cntrl:]]'
    OR clean_nickname ~ '@'
    OR clean_nickname ~* '\mhttps?://'
    OR clean_nickname ~* '\mwww\.'
  THEN
    RAISE EXCEPTION 'Nickname must be 2-24 characters and cannot contain emails or links.'
      USING ERRCODE = '22023';
  END IF;

  IF p_avatar_id IS NULL OR p_avatar_id NOT IN (
    'pulse', 'scholar', 'rounds', 'cardio', 'calm', 'scope', 'notes', 'anatomy'
  ) THEN
    RAISE EXCEPTION 'Choose a valid profile avatar.' USING ERRCODE = '22023';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.user_preferences preferences
    WHERE lower(btrim(preferences.nickname)) = lower(clean_nickname)
      AND preferences.user_id <> current_user_id
  ) THEN
    RAISE EXCEPTION 'Nickname is already taken.' USING ERRCODE = '23505';
  END IF;

  INSERT INTO public.user_preferences (
    user_id,
    anonymous,
    nickname,
    avatar_id,
    profile_setup_version,
    updated_at
  )
  VALUES (
    current_user_id,
    false,
    clean_nickname,
    p_avatar_id,
    1,
    now()
  )
  ON CONFLICT (user_id)
  DO UPDATE SET
    anonymous = false,
    nickname = EXCLUDED.nickname,
    avatar_id = EXCLUDED.avatar_id,
    profile_setup_version = 1,
    updated_at = now()
  RETURNING *
  INTO saved_preferences;

  RETURN jsonb_build_object(
    'anonymous', false,
    'selected_section', saved_preferences.selected_section,
    'nickname', saved_preferences.nickname,
    'avatar_id', saved_preferences.avatar_id,
    'profile_setup_version', saved_preferences.profile_setup_version,
    'updated_at', saved_preferences.updated_at
  );
END;
$$;

REVOKE ALL ON FUNCTION public.complete_profile_setup(TEXT, TEXT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.complete_profile_setup(TEXT, TEXT) TO authenticated;

DROP FUNCTION IF EXISTS public.get_leaderboard(TEXT);

CREATE FUNCTION public.get_leaderboard(p_section TEXT DEFAULT '401')
RETURNS TABLE (
  user_id                     UUID,
  display_name                TEXT,
  avatar_id                   TEXT,
  anonymous                   BOOLEAN,
  total_score                 BIGINT,
  mcqs_count                  BIGINT,
  quizzes_completed           BIGINT,
  correct_answers             BIGINT,
  lifetime_score              BIGINT,
  lifetime_mcqs_count         BIGINT,
  lifetime_quizzes_completed  BIGINT,
  lifetime_correct_answers    BIGINT,
  season_id                   BIGINT,
  season_name                 TEXT
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  WITH active_season AS (
    SELECT season.id, season.name, season.scope_topic_label
    FROM public.leaderboard_seasons season
    WHERE season.section = p_section
      AND season.active
      AND season.starts_at <= now()
      AND (season.ends_at IS NULL OR season.ends_at > now())
    ORDER BY season.starts_at DESC
    LIMIT 1
  ),
  lifetime_scores AS (
    SELECT
      scores.user_id,
      COALESCE(SUM(scores.best_score), 0)::BIGINT AS total_score
    FROM public.user_lifetime_scores scores
    WHERE scores.section = p_section
    GROUP BY scores.user_id
  ),
  lifetime_progress AS (
    SELECT
      progress.user_id,
      COUNT(DISTINCT progress.topic_label) FILTER (WHERE progress.answered_count > 0)::BIGINT AS topics_count,
      COUNT(*) FILTER (WHERE progress.completed)::BIGINT AS quizzes_count
    FROM public.user_mcq_progress progress
    WHERE progress.section = p_section
    GROUP BY progress.user_id
  ),
  season_scores AS (
    SELECT
      scores.user_id,
      COALESCE(SUM(scores.best_score), 0)::BIGINT AS total_score,
      COUNT(DISTINCT scores.topic_label)::BIGINT AS topics_count,
      COUNT(*)::BIGINT AS quizzes_count
    FROM public.user_season_scores scores
    JOIN active_season season ON season.id = scores.season_id
    GROUP BY scores.user_id
  ),
  eligible_students AS (
    SELECT
      users.id,
      preferences.nickname,
      preferences.avatar_id,
      COALESCE(lifetime.total_score, 0)::BIGINT AS lifetime_score,
      COALESCE(progress_stats.topics_count, 0)::BIGINT AS lifetime_topics,
      COALESCE(progress_stats.quizzes_count, 0)::BIGINT AS lifetime_quizzes,
      COALESCE(season_scores.total_score, 0)::BIGINT AS season_score,
      COALESCE(season_scores.topics_count, 0)::BIGINT AS season_topics,
      COALESCE(season_scores.quizzes_count, 0)::BIGINT AS season_quizzes,
      season.id AS active_season_id,
      season.name AS active_season_name
    FROM auth.users users
    JOIN public.user_preferences preferences
      ON preferences.user_id = users.id
      AND preferences.profile_setup_version >= 1
      AND preferences.anonymous = false
      AND NULLIF(btrim(preferences.nickname), '') IS NOT NULL
      AND NULLIF(preferences.avatar_id, '') IS NOT NULL
    LEFT JOIN lifetime_scores lifetime ON lifetime.user_id = users.id
    LEFT JOIN lifetime_progress progress_stats ON progress_stats.user_id = users.id
    LEFT JOIN season_scores ON season_scores.user_id = users.id
    LEFT JOIN active_season season ON true
  )
  SELECT
    CASE WHEN student.id = (SELECT auth.uid()) THEN student.id ELSE NULL END,
    btrim(student.nickname),
    student.avatar_id,
    false,
    CASE
      WHEN student.active_season_id IS NOT NULL THEN student.season_score
      ELSE student.lifetime_score
    END,
    CASE
      WHEN student.active_season_id IS NOT NULL THEN student.season_topics
      ELSE student.lifetime_topics
    END,
    CASE
      WHEN student.active_season_id IS NOT NULL THEN student.season_quizzes
      ELSE student.lifetime_quizzes
    END,
    CASE
      WHEN student.active_season_id IS NOT NULL THEN student.season_score
      ELSE student.lifetime_score
    END,
    student.lifetime_score,
    student.lifetime_topics,
    student.lifetime_quizzes,
    student.lifetime_score,
    student.active_season_id,
    student.active_season_name
  FROM eligible_students student
  WHERE (SELECT auth.uid()) IS NOT NULL
    AND (
      CASE
        WHEN student.active_season_id IS NOT NULL THEN student.season_score
        ELSE student.lifetime_score
      END > 0
      OR student.id = (SELECT auth.uid())
    )
  ORDER BY
    CASE
      WHEN student.active_season_id IS NOT NULL THEN student.season_score
      ELSE student.lifetime_score
    END DESC,
    lower(student.nickname),
    student.id;
$$;

REVOKE ALL ON FUNCTION public.get_leaderboard(TEXT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_leaderboard(TEXT) TO authenticated;

DROP FUNCTION IF EXISTS public.get_recent_mcq_activity(TEXT, INTEGER);

CREATE FUNCTION public.get_recent_mcq_activity(
  p_section TEXT DEFAULT '401',
  p_limit INTEGER DEFAULT 8
)
RETURNS TABLE (
  display_name      TEXT,
  avatar_id         TEXT,
  topic_label       TEXT,
  source_label      TEXT,
  answered_count    INTEGER,
  total_questions   INTEGER,
  completed         BOOLEAN,
  updated_at        TIMESTAMPTZ,
  rank              BIGINT
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
  WITH active_season AS (
    SELECT season.id, season.scope_topic_label, season.starts_at
    FROM public.leaderboard_seasons season
    WHERE season.section = p_section
      AND season.active
      AND season.starts_at <= now()
      AND (season.ends_at IS NULL OR season.ends_at > now())
    ORDER BY season.starts_at DESC
    LIMIT 1
  ),
  score_totals AS (
    SELECT scores.user_id, SUM(scores.best_score)::BIGINT AS total_score
    FROM public.user_season_scores scores
    JOIN active_season season ON season.id = scores.season_id
    GROUP BY scores.user_id
    HAVING SUM(scores.best_score) > 0
    UNION ALL
    SELECT scores.user_id, SUM(scores.best_score)::BIGINT AS total_score
    FROM public.user_lifetime_scores scores
    WHERE scores.section = p_section
      AND NOT EXISTS (SELECT 1 FROM active_season)
    GROUP BY scores.user_id
    HAVING SUM(scores.best_score) > 0
  ),
  ranked_users AS (
    SELECT
      totals.user_id,
      ROW_NUMBER() OVER (ORDER BY totals.total_score DESC, totals.user_id) AS rank
    FROM score_totals totals
  ),
  recent_per_student AS (
    SELECT DISTINCT ON (progress.user_id)
      progress.user_id,
      progress.topic_label,
      progress.source_label,
      progress.answered_count,
      progress.total_questions,
      progress.completed,
      progress.updated_at
    FROM public.user_mcq_progress progress
    LEFT JOIN active_season season ON true
    WHERE progress.section = p_section
      AND progress.completed
      AND progress.score > 0
      AND progress.updated_at >= now() - INTERVAL '15 minutes'
      AND (
        season.id IS NULL
        OR (
          progress.topic_label = season.scope_topic_label
          AND progress.attempt_started_at >= season.starts_at
        )
      )
    ORDER BY progress.user_id, progress.updated_at DESC
  )
  SELECT
    btrim(preferences.nickname),
    preferences.avatar_id,
    recent.topic_label,
    recent.source_label,
    recent.answered_count,
    recent.total_questions,
    recent.completed,
    recent.updated_at,
    ranked.rank
  FROM recent_per_student recent
  JOIN ranked_users ranked ON ranked.user_id = recent.user_id
  JOIN public.user_preferences preferences
    ON preferences.user_id = recent.user_id
    AND preferences.profile_setup_version >= 1
    AND preferences.anonymous = false
    AND NULLIF(btrim(preferences.nickname), '') IS NOT NULL
    AND NULLIF(preferences.avatar_id, '') IS NOT NULL
  WHERE (SELECT auth.uid()) IS NOT NULL
  ORDER BY recent.updated_at DESC
  LIMIT GREATEST(1, LEAST(COALESCE(p_limit, 8), 12));
$$;

REVOKE ALL ON FUNCTION public.get_recent_mcq_activity(TEXT, INTEGER) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_recent_mcq_activity(TEXT, INTEGER) TO authenticated;
